apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app
resources:
  - namespace.yaml
  - secrets.yaml
  - redis-deployment.yaml
  - deployment-oauth2-proxy.yaml
  - service-oauth2-proxy.yaml
  - ingress-oauth2-proxy.yaml
  - ingress.yaml
  - sample-app.yaml
  - backend-deployment.yaml # NUEVO o parte de sample-app.yaml
  - backend-service.yaml    # NUEVO o parte de sample-app.yaml
  - frontend-deployment.yaml # NUEVO o parte de sample-app.yaml
  - frontend-service.yaml   # NUEVO o parte de sample-app.yaml
  - postgres-secret.yaml # NUEVO o parte de sample-app.yaml
  