apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy
  namespace: app
type: Opaque
data:
  client-id: OTQzMTA2NzM1MTg0LWNpMzAxMnU3NmdoMGd1cTEyMjRtN2N2OXM1ZmExb2JrLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
  client-secret: R09DU1BYLW1oOTNvYmhidlRLV29KX3NMcG94V2ZOQTJJalg=
  cookie-secret: QjRqZWZNMUdmRnpGOHZNR0R1djZZZz09 # Este puede ser cualquier cadena aleatoria codificada en Base64, el que tenías está bien.

